//Nueva solicitud cliente
get http://localhost:3000/api/catalogo/temas
content-type: application/json

{

}
###
//datos cliente dueño con tema
get http://localhost:3000/api/catalogo/temas/solicitud/pacific
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImNsaWVudGUiLCJuYW1lIjoiQ2xpZW50ZSIsImVtYWlsIjoiY2xpZW50ZUB5b3BtYWlsLmNvbSIsIl9pZCI6IjYwNzc0YTQzMWU4NzczMWZlY2VkYWJiOCIsImVzdGFkbyI6ZmFsc2UsImlhdCI6MTYxODQzNzU4NSwiZXhwIjoxNjE4NTIzOTg1fQ.6V7ulyXo_hHZsngehs52NjPg6TC7XXRhY-aW8xc2rio

{

}