//Nueva solicitud cliente
get http://localhost:3000/api/catalogo/temas
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImNsaWVudGUiLCJuYW1lIjoiR2FicmllbCBHcmFjaWEgTWFycXVleiIsImVtYWlsIjoiY2xpZW50ZUB5b3BtYWlsLmNvbSIsImVzdGFkbyI6dHJ1ZSwiaWF0IjoxNjE2ODExNTQ0LCJleHAiOjE2MTY4OTc5NDR9.AAZzMwrHo3R4T01CgqnYKW8fX5dW6Pf0p0T4em1QcaU

{

}
###
//datos cliente dueño con tema
get http://localhost:3000/api/catalogo/temas/solicitud/pacific
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImNsaWVudGUiLCJuYW1lIjoiQ2x1YiBTb2x1Y2lvbmVzIiwiZW1haWwiOiJjbHViQHlvcG1haWwuY29tIiwiX2lkIjoiNjA1YTY3Zjg2Yjk1NTExNTA2MTJmNGZjIiwiZXN0YWRvIjp0cnVlLCJpYXQiOjE2MTc5OTY4NjEsImV4cCI6MTYxODA4MzI2MX0.FUDmxtBq5bBBpnzU054SHWtXAUs_6VS_5krH_KOiil8

{

}