
post http://localhost:3000/api/solicitudes/
content-type: application/json

{
"tipo_venta": "Catalogo Publicado",
"abreviacion": "ACE2",
"descripcion" : "El catalogo es público para todos"
}


###

post http://localhost:3000/api/ventas/datos-envio
content-type: application/json

{
    "usuario": "60774b251e87731fecedabba",
    "telefono": "+573147733106",
    "direccion_completa": "Cra 7 # 10-72, ",
    "otras_indicaciones": "Casa 12, esquinera.",
    "departamento": "dep",
    "provincia": "distrito",
    "distrito": "prov"
}


###
///Consuiltar datos de envio
get http://localhost:3000/api/ventas/datos-envio/60774b251e87731fecedabba
content-type: application/json

{

}


###
/// Crear nueva venta ///

post http://localhost:3000/api/ventas
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImFkbWluIiwibmFtZSI6IkFsZXhpcyIsImVtYWlsIjoiYWxleGlzMTFkaW1lbkBnbWFpbC5jb20iLCJfaWQiOiI2MDc3NGIyNTFlODc3MzFmZWNlZGFiYmEiLCJlc3RhZG8iOnRydWUsImlhdCI6MTYyNDk1MTgxNSwiZXhwIjoxNjI1MDM4MjE1fQ.mJ33aGygtqLR4G7q58wxHZX3KNemONkhkWvtVDyOE34

{
 "comprador": "60774b251e87731fecedabba",
 "tipo_pago": 0,
 "nombreProducto": "Moneda de Oro",
 "total" : 450,

 "productos": [

          {
         "producto": "60da608a6a83d20bbf40eab0",
         "id_tamanio": "60da608a6a83d20bbf40eab1",
         "id_color": "60da608a6a83d20bbf40eab2",
         "cantidad": 2,
         "tipo_envio": "Provincias",
         "valor_envio": 20
     }
     ]


}
